/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: nvcm.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "nvcm.pb-c.h"
void   nvcmsg__init
                     (NVCMsg         *message)
{
  static NVCMsg init_value = NVCMSG__INIT;
  *message = init_value;
}
size_t nvcmsg__get_packed_size
                     (const NVCMsg *message)
{
  assert(message->base.descriptor == &nvcmsg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nvcmsg__pack
                     (const NVCMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nvcmsg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nvcmsg__pack_to_buffer
                     (const NVCMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nvcmsg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NVCMsg *
       nvcmsg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NVCMsg *)
     protobuf_c_message_unpack (&nvcmsg__descriptor,
                                allocator, len, data);
}
void   nvcmsg__free_unpacked
                     (NVCMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &nvcmsg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   add_request__init
                     (AddRequest         *message)
{
  static AddRequest init_value = ADD_REQUEST__INIT;
  *message = init_value;
}
size_t add_request__get_packed_size
                     (const AddRequest *message)
{
  assert(message->base.descriptor == &add_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t add_request__pack
                     (const AddRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &add_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t add_request__pack_to_buffer
                     (const AddRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &add_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AddRequest *
       add_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AddRequest *)
     protobuf_c_message_unpack (&add_request__descriptor,
                                allocator, len, data);
}
void   add_request__free_unpacked
                     (AddRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &add_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   add_response__init
                     (AddResponse         *message)
{
  static AddResponse init_value = ADD_RESPONSE__INIT;
  *message = init_value;
}
size_t add_response__get_packed_size
                     (const AddResponse *message)
{
  assert(message->base.descriptor == &add_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t add_response__pack
                     (const AddResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &add_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t add_response__pack_to_buffer
                     (const AddResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &add_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AddResponse *
       add_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AddResponse *)
     protobuf_c_message_unpack (&add_response__descriptor,
                                allocator, len, data);
}
void   add_response__free_unpacked
                     (AddResponse *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &add_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   del_request__init
                     (DelRequest         *message)
{
  static DelRequest init_value = DEL_REQUEST__INIT;
  *message = init_value;
}
size_t del_request__get_packed_size
                     (const DelRequest *message)
{
  assert(message->base.descriptor == &del_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t del_request__pack
                     (const DelRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &del_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t del_request__pack_to_buffer
                     (const DelRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &del_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DelRequest *
       del_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DelRequest *)
     protobuf_c_message_unpack (&del_request__descriptor,
                                allocator, len, data);
}
void   del_request__free_unpacked
                     (DelRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &del_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   del_response__init
                     (DelResponse         *message)
{
  static DelResponse init_value = DEL_RESPONSE__INIT;
  *message = init_value;
}
size_t del_response__get_packed_size
                     (const DelResponse *message)
{
  assert(message->base.descriptor == &del_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t del_response__pack
                     (const DelResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &del_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t del_response__pack_to_buffer
                     (const DelResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &del_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DelResponse *
       del_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DelResponse *)
     protobuf_c_message_unpack (&del_response__descriptor,
                                allocator, len, data);
}
void   del_response__free_unpacked
                     (DelResponse *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &del_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   modify_request__init
                     (ModifyRequest         *message)
{
  static ModifyRequest init_value = MODIFY_REQUEST__INIT;
  *message = init_value;
}
size_t modify_request__get_packed_size
                     (const ModifyRequest *message)
{
  assert(message->base.descriptor == &modify_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t modify_request__pack
                     (const ModifyRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &modify_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t modify_request__pack_to_buffer
                     (const ModifyRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &modify_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ModifyRequest *
       modify_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ModifyRequest *)
     protobuf_c_message_unpack (&modify_request__descriptor,
                                allocator, len, data);
}
void   modify_request__free_unpacked
                     (ModifyRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &modify_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   modify_response__init
                     (ModifyResponse         *message)
{
  static ModifyResponse init_value = MODIFY_RESPONSE__INIT;
  *message = init_value;
}
size_t modify_response__get_packed_size
                     (const ModifyResponse *message)
{
  assert(message->base.descriptor == &modify_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t modify_response__pack
                     (const ModifyResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &modify_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t modify_response__pack_to_buffer
                     (const ModifyResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &modify_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ModifyResponse *
       modify_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ModifyResponse *)
     protobuf_c_message_unpack (&modify_response__descriptor,
                                allocator, len, data);
}
void   modify_response__free_unpacked
                     (ModifyResponse *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &modify_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   search_request__init
                     (SearchRequest         *message)
{
  static SearchRequest init_value = SEARCH_REQUEST__INIT;
  *message = init_value;
}
size_t search_request__get_packed_size
                     (const SearchRequest *message)
{
  assert(message->base.descriptor == &search_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t search_request__pack
                     (const SearchRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &search_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t search_request__pack_to_buffer
                     (const SearchRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &search_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SearchRequest *
       search_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SearchRequest *)
     protobuf_c_message_unpack (&search_request__descriptor,
                                allocator, len, data);
}
void   search_request__free_unpacked
                     (SearchRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &search_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   search_response__init
                     (SearchResponse         *message)
{
  static SearchResponse init_value = SEARCH_RESPONSE__INIT;
  *message = init_value;
}
size_t search_response__get_packed_size
                     (const SearchResponse *message)
{
  assert(message->base.descriptor == &search_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t search_response__pack
                     (const SearchResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &search_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t search_response__pack_to_buffer
                     (const SearchResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &search_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SearchResponse *
       search_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SearchResponse *)
     protobuf_c_message_unpack (&search_response__descriptor,
                                allocator, len, data);
}
void   search_response__free_unpacked
                     (SearchResponse *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &search_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   node_connect_info__init
                     (NodeConnectInfo         *message)
{
  static NodeConnectInfo init_value = NODE_CONNECT_INFO__INIT;
  *message = init_value;
}
size_t node_connect_info__get_packed_size
                     (const NodeConnectInfo *message)
{
  assert(message->base.descriptor == &node_connect_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t node_connect_info__pack
                     (const NodeConnectInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &node_connect_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t node_connect_info__pack_to_buffer
                     (const NodeConnectInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &node_connect_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NodeConnectInfo *
       node_connect_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NodeConnectInfo *)
     protobuf_c_message_unpack (&node_connect_info__descriptor,
                                allocator, len, data);
}
void   node_connect_info__free_unpacked
                     (NodeConnectInfo *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &node_connect_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   object__init
                     (Object         *message)
{
  static Object init_value = OBJECT__INIT;
  *message = init_value;
}
size_t object__get_packed_size
                     (const Object *message)
{
  assert(message->base.descriptor == &object__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t object__pack
                     (const Object *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &object__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t object__pack_to_buffer
                     (const Object *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &object__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Object *
       object__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Object *)
     protobuf_c_message_unpack (&object__descriptor,
                                allocator, len, data);
}
void   object__free_unpacked
                     (Object *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &object__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   client__init
                     (Client         *message)
{
  static Client init_value = CLIENT__INIT;
  *message = init_value;
}
size_t client__get_packed_size
                     (const Client *message)
{
  assert(message->base.descriptor == &client__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client__pack
                     (const Client *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client__pack_to_buffer
                     (const Client *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Client *
       client__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Client *)
     protobuf_c_message_unpack (&client__descriptor,
                                allocator, len, data);
}
void   client__free_unpacked
                     (Client *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &client__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   context__init
                     (Context         *message)
{
  static Context init_value = CONTEXT__INIT;
  *message = init_value;
}
size_t context__get_packed_size
                     (const Context *message)
{
  assert(message->base.descriptor == &context__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t context__pack
                     (const Context *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &context__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t context__pack_to_buffer
                     (const Context *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &context__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Context *
       context__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Context *)
     protobuf_c_message_unpack (&context__descriptor,
                                allocator, len, data);
}
void   context__free_unpacked
                     (Context *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &context__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   node__init
                     (Node         *message)
{
  static Node init_value = NODE__INIT;
  *message = init_value;
}
size_t node__get_packed_size
                     (const Node *message)
{
  assert(message->base.descriptor == &node__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t node__pack
                     (const Node *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &node__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t node__pack_to_buffer
                     (const Node *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &node__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Node *
       node__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Node *)
     protobuf_c_message_unpack (&node__descriptor,
                                allocator, len, data);
}
void   node__free_unpacked
                     (Node *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &node__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor nvcmsg__field_descriptors[10] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(NVCMsg, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addRequest",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NVCMsg, op_case),
    offsetof(NVCMsg, addrequest),
    &add_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addResponse",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NVCMsg, op_case),
    offsetof(NVCMsg, addresponse),
    &add_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delRequest",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NVCMsg, op_case),
    offsetof(NVCMsg, delrequest),
    &del_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delResponse",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NVCMsg, op_case),
    offsetof(NVCMsg, delresponse),
    &del_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "modifyRequest",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NVCMsg, op_case),
    offsetof(NVCMsg, modifyrequest),
    &modify_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "modifyResponse",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NVCMsg, op_case),
    offsetof(NVCMsg, modifyresponse),
    &modify_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "searchRequest",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NVCMsg, op_case),
    offsetof(NVCMsg, searchrequest),
    &search_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "searchResponse",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NVCMsg, op_case),
    offsetof(NVCMsg, searchresponse),
    &search_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nodeConnectInfo",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NVCMsg, op_case),
    offsetof(NVCMsg, nodeconnectinfo),
    &node_connect_info__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nvcmsg__field_indices_by_name[] = {
  1,   /* field[1] = addRequest */
  2,   /* field[2] = addResponse */
  3,   /* field[3] = delRequest */
  4,   /* field[4] = delResponse */
  5,   /* field[5] = modifyRequest */
  6,   /* field[6] = modifyResponse */
  9,   /* field[9] = nodeConnectInfo */
  7,   /* field[7] = searchRequest */
  8,   /* field[8] = searchResponse */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange nvcmsg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor nvcmsg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NVCMsg",
  "NVCMsg",
  "NVCMsg",
  "",
  sizeof(NVCMsg),
  10,
  nvcmsg__field_descriptors,
  nvcmsg__field_indices_by_name,
  1,  nvcmsg__number_ranges,
  (ProtobufCMessageInit) nvcmsg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor add_request__field_descriptors[1] =
{
  {
    "object",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(AddRequest, object),
    &object__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned add_request__field_indices_by_name[] = {
  0,   /* field[0] = object */
};
static const ProtobufCIntRange add_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor add_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AddRequest",
  "AddRequest",
  "AddRequest",
  "",
  sizeof(AddRequest),
  1,
  add_request__field_descriptors,
  add_request__field_indices_by_name,
  1,  add_request__number_ranges,
  (ProtobufCMessageInit) add_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define add_response__field_descriptors NULL
#define add_response__field_indices_by_name NULL
#define add_response__number_ranges NULL
const ProtobufCMessageDescriptor add_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AddResponse",
  "AddResponse",
  "AddResponse",
  "",
  sizeof(AddResponse),
  0,
  add_response__field_descriptors,
  add_response__field_indices_by_name,
  0,  add_response__number_ranges,
  (ProtobufCMessageInit) add_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor del_request__field_descriptors[1] =
{
  {
    "object",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DelRequest, object),
    &object__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned del_request__field_indices_by_name[] = {
  0,   /* field[0] = object */
};
static const ProtobufCIntRange del_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor del_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DelRequest",
  "DelRequest",
  "DelRequest",
  "",
  sizeof(DelRequest),
  1,
  del_request__field_descriptors,
  del_request__field_indices_by_name,
  1,  del_request__number_ranges,
  (ProtobufCMessageInit) del_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define del_response__field_descriptors NULL
#define del_response__field_indices_by_name NULL
#define del_response__number_ranges NULL
const ProtobufCMessageDescriptor del_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DelResponse",
  "DelResponse",
  "DelResponse",
  "",
  sizeof(DelResponse),
  0,
  del_response__field_descriptors,
  del_response__field_indices_by_name,
  0,  del_response__number_ranges,
  (ProtobufCMessageInit) del_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor modify_request__field_descriptors[1] =
{
  {
    "object",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ModifyRequest, object),
    &object__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned modify_request__field_indices_by_name[] = {
  0,   /* field[0] = object */
};
static const ProtobufCIntRange modify_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor modify_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ModifyRequest",
  "ModifyRequest",
  "ModifyRequest",
  "",
  sizeof(ModifyRequest),
  1,
  modify_request__field_descriptors,
  modify_request__field_indices_by_name,
  1,  modify_request__number_ranges,
  (ProtobufCMessageInit) modify_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define modify_response__field_descriptors NULL
#define modify_response__field_indices_by_name NULL
#define modify_response__number_ranges NULL
const ProtobufCMessageDescriptor modify_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ModifyResponse",
  "ModifyResponse",
  "ModifyResponse",
  "",
  sizeof(ModifyResponse),
  0,
  modify_response__field_descriptors,
  modify_response__field_indices_by_name,
  0,  modify_response__number_ranges,
  (ProtobufCMessageInit) modify_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor search_request__field_descriptors[2] =
{
  {
    "searchtype",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SearchRequest, searchtype),
    &search_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "object",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SearchRequest, object),
    &object__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned search_request__field_indices_by_name[] = {
  1,   /* field[1] = object */
  0,   /* field[0] = searchtype */
};
static const ProtobufCIntRange search_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor search_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SearchRequest",
  "SearchRequest",
  "SearchRequest",
  "",
  sizeof(SearchRequest),
  2,
  search_request__field_descriptors,
  search_request__field_indices_by_name,
  1,  search_request__number_ranges,
  (ProtobufCMessageInit) search_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor search_response__field_descriptors[2] =
{
  {
    "searchtype",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SearchResponse, searchtype),
    &search_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "object",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SearchResponse, object),
    &object__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned search_response__field_indices_by_name[] = {
  1,   /* field[1] = object */
  0,   /* field[0] = searchtype */
};
static const ProtobufCIntRange search_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor search_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SearchResponse",
  "SearchResponse",
  "SearchResponse",
  "",
  sizeof(SearchResponse),
  2,
  search_response__field_descriptors,
  search_response__field_indices_by_name,
  1,  search_response__number_ranges,
  (ProtobufCMessageInit) search_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define node_connect_info__field_descriptors NULL
#define node_connect_info__field_indices_by_name NULL
#define node_connect_info__number_ranges NULL
const ProtobufCMessageDescriptor node_connect_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NodeConnectInfo",
  "NodeConnectInfo",
  "NodeConnectInfo",
  "",
  sizeof(NodeConnectInfo),
  0,
  node_connect_info__field_descriptors,
  node_connect_info__field_indices_by_name,
  0,  node_connect_info__number_ranges,
  (ProtobufCMessageInit) node_connect_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor object__field_descriptors[3] =
{
  {
    "client",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Object, object_case),
    offsetof(Object, client),
    &client__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "context",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Object, object_case),
    offsetof(Object, context),
    &context__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "node",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Object, object_case),
    offsetof(Object, node),
    &node__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned object__field_indices_by_name[] = {
  0,   /* field[0] = client */
  1,   /* field[1] = context */
  2,   /* field[2] = node */
};
static const ProtobufCIntRange object__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor object__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Object",
  "Object",
  "Object",
  "",
  sizeof(Object),
  3,
  object__field_descriptors,
  object__field_indices_by_name,
  1,  object__number_ranges,
  (ProtobufCMessageInit) object__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor client__field_descriptors[3] =
{
  {
    "email",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Client, email),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pwd",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Client, pwd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "apikey",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Client, apikey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client__field_indices_by_name[] = {
  2,   /* field[2] = apikey */
  0,   /* field[0] = email */
  1,   /* field[1] = pwd */
};
static const ProtobufCIntRange client__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor client__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Client",
  "Client",
  "Client",
  "",
  sizeof(Client),
  3,
  client__field_descriptors,
  client__field_indices_by_name,
  1,  client__number_ranges,
  (ProtobufCMessageInit) client__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor context__field_descriptors[3] =
{
  {
    "clientid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Context, clientid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Context, has_id),
    offsetof(Context, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "description",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Context, description),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned context__field_indices_by_name[] = {
  0,   /* field[0] = clientid */
  2,   /* field[2] = description */
  1,   /* field[1] = id */
};
static const ProtobufCIntRange context__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor context__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Context",
  "Context",
  "Context",
  "",
  sizeof(Context),
  3,
  context__field_descriptors,
  context__field_indices_by_name,
  1,  context__number_ranges,
  (ProtobufCMessageInit) context__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor node__field_descriptors[6] =
{
  {
    "contextid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Node, has_contextid),
    offsetof(Node, contextid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "description",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Node, description),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uuid",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Node, uuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "provkey",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Node, provkey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipaddr",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Node, ipaddr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Node, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned node__field_indices_by_name[] = {
  0,   /* field[0] = contextid */
  1,   /* field[1] = description */
  4,   /* field[4] = ipaddr */
  3,   /* field[3] = provkey */
  5,   /* field[5] = status */
  2,   /* field[2] = uuid */
};
static const ProtobufCIntRange node__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor node__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Node",
  "Node",
  "Node",
  "",
  sizeof(Node),
  6,
  node__field_descriptors,
  node__field_indices_by_name,
  1,  node__number_ranges,
  (ProtobufCMessageInit) node__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue search_type__enum_values_by_number[3] =
{
  { "OBJECT", "SEARCH_TYPE__OBJECT", 0 },
  { "SEQUENCE", "SEARCH_TYPE__SEQUENCE", 1 },
  { "ALL", "SEARCH_TYPE__ALL", 2 },
};
static const ProtobufCIntRange search_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex search_type__enum_values_by_name[3] =
{
  { "ALL", 2 },
  { "OBJECT", 0 },
  { "SEQUENCE", 1 },
};
const ProtobufCEnumDescriptor search_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SearchType",
  "SearchType",
  "SearchType",
  "",
  3,
  search_type__enum_values_by_number,
  3,
  search_type__enum_values_by_name,
  1,
  search_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
