/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "DNDS"
 * 	found in "./dnds.asn1"
 */

#ifndef	_AddRequest_H_
#define	_AddRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DNDSObject.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AddRequest */
typedef DNDSObject_t	 AddRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AddRequest;
asn_struct_free_f AddRequest_free;
asn_struct_print_f AddRequest_print;
asn_constr_check_f AddRequest_constraint;
ber_type_decoder_f AddRequest_decode_ber;
der_type_encoder_f AddRequest_encode_der;
xer_type_decoder_f AddRequest_decode_xer;
xer_type_encoder_f AddRequest_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AddRequest_H_ */
#include <asn_internal.h>
