/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "DNDS"
 * 	found in "dnds.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_AuthResponse_H_
#define	_AuthResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DNDSResult.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AuthResponse */
typedef DNDSResult_t	 AuthResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AuthResponse;
asn_struct_free_f AuthResponse_free;
asn_struct_print_f AuthResponse_print;
asn_constr_check_f AuthResponse_constraint;
ber_type_decoder_f AuthResponse_decode_ber;
der_type_encoder_f AuthResponse_encode_der;
xer_type_decoder_f AuthResponse_decode_xer;
xer_type_encoder_f AuthResponse_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AuthResponse_H_ */
#include <asn_internal.h>
