/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "DNDS"
 * 	found in "dnds.asn1"
 */

#ifndef	_Client_H_
#define	_Client_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <PrintableString.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Client */
typedef struct Client {
	unsigned long	 id;
	PrintableString_t	*username	/* OPTIONAL */;
	PrintableString_t	*password	/* OPTIONAL */;
	PrintableString_t	*firstname	/* OPTIONAL */;
	PrintableString_t	*lastname	/* OPTIONAL */;
	PrintableString_t	*email	/* OPTIONAL */;
	PrintableString_t	*company	/* OPTIONAL */;
	PrintableString_t	*phone	/* OPTIONAL */;
	PrintableString_t	*country	/* OPTIONAL */;
	PrintableString_t	*stateProvince	/* OPTIONAL */;
	PrintableString_t	*city	/* OPTIONAL */;
	PrintableString_t	*postalCode	/* OPTIONAL */;
	long	*status	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Client_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_id_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Client;

#ifdef __cplusplus
}
#endif

#endif	/* _Client_H_ */
#include <asn_internal.h>
