/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "DNDS"
 * 	found in "dnds.asn1"
 */

#ifndef	_Context_H_
#define	_Context_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <PrintableString.h>
#include <BIT_STRING.h>
#include <NULL.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Context */
typedef struct Context {
	unsigned long	 id;
	unsigned long	 ippoolId;
	PrintableString_t	*dnsZone	/* OPTIONAL */;
	unsigned long	*dnsSerial	/* OPTIONAL */;
	PrintableString_t	*vhost	/* OPTIONAL */;
	PrintableString_t	*certificate	/* OPTIONAL */;
	BIT_STRING_t	*certificateKey	/* OPTIONAL */;
	NULL_t	*trustList	/* OPTIONAL */;
	NULL_t	*revokeList	/* OPTIONAL */;
	PrintableString_t	*description	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Context_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_id_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ippoolId_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_dnsSerial_5;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Context;

#ifdef __cplusplus
}
#endif

#endif	/* _Context_H_ */
#include <asn_internal.h>
