/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "DNDS"
 * 	found in "dnds.asn1"
 */

#ifndef	_DNDSObject_H_
#define	_DNDSObject_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Acl.h"
#include "AclGroup.h"
#include "IpPool.h"
#include "Context.h"
#include "Host.h"
#include "Node.h"
#include "Peer.h"
#include "Permission.h"
#include "Client.h"
#include "WebCredential.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DNDSObject_PR {
	DNDSObject_PR_NOTHING,	/* No components present */
	DNDSObject_PR_acl,
	DNDSObject_PR_aclgroup,
	DNDSObject_PR_ippool,
	DNDSObject_PR_context,
	DNDSObject_PR_host,
	DNDSObject_PR_node,
	DNDSObject_PR_peer,
	DNDSObject_PR_permission,
	DNDSObject_PR_client,
	DNDSObject_PR_webcredential,
	/* Extensions may appear below */
	
} DNDSObject_PR;

/* DNDSObject */
typedef struct DNDSObject {
	DNDSObject_PR present;
	union DNDSObject_u {
		Acl_t	 acl;
		AclGroup_t	 aclgroup;
		IpPool_t	 ippool;
		Context_t	 context;
		Host_t	 host;
		Node_t	 node;
		Peer_t	 peer;
		Permission_t	 permission;
		Client_t	 client;
		WebCredential_t	 webcredential;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DNDSObject_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DNDSObject;

#ifdef __cplusplus
}
#endif

#endif	/* _DNDSObject_H_ */
#include <asn_internal.h>
