/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "DNDS"
 * 	found in "dnds.asn1"
 */

#ifndef	_DSObject_H_
#define	_DSObject_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Acl.h"
#include "AclGroup.h"
#include "IpPool.h"
#include "Context.h"
#include "Host.h"
#include "Node.h"
#include "Peer.h"
#include "Permission.h"
#include "User.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DSObject_PR {
	DSObject_PR_NOTHING,	/* No components present */
	DSObject_PR_acl,
	DSObject_PR_aclgroup,
	DSObject_PR_ippool,
	DSObject_PR_context,
	DSObject_PR_host,
	DSObject_PR_node,
	DSObject_PR_peer,
	DSObject_PR_permission,
	DSObject_PR_user
} DSObject_PR;

/* DSObject */
typedef struct DSObject {
	DSObject_PR present;
	union DSObject_u {
		Acl_t	 acl;
		AclGroup_t	 aclgroup;
		IpPool_t	 ippool;
		Context_t	 context;
		Host_t	 host;
		Node_t	 node;
		Peer_t	 peer;
		Permission_t	 permission;
		User_t	 user;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DSObject_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DSObject;

#ifdef __cplusplus
}
#endif

#endif	/* _DSObject_H_ */
#include <asn_internal.h>
