/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "DNDS"
 * 	found in "./dnds.asn1"
 */

#ifndef	_Host_H_
#define	_Host_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <PrintableString.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Host */
typedef struct Host {
	unsigned long	 id;
	unsigned long	 contextId;
	unsigned long	 peerId;
	PrintableString_t	*name	/* OPTIONAL */;
	OCTET_STRING_t	*macAddress	/* OPTIONAL */;
	OCTET_STRING_t	*ipAddress	/* OPTIONAL */;
	long	*status	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Host_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_id_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_contextId_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_peerId_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Host;

#ifdef __cplusplus
}
#endif

#endif	/* _Host_H_ */
#include <asn_internal.h>
