/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "DNDS"
 * 	found in "./dnds.asn1"
 */

#ifndef	_IpPool_H_
#define	_IpPool_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IpPool */
typedef struct IpPool {
	unsigned long	 id;
	OCTET_STRING_t	*ipLocal	/* OPTIONAL */;
	OCTET_STRING_t	*ipBegin	/* OPTIONAL */;
	OCTET_STRING_t	*ipEnd	/* OPTIONAL */;
	OCTET_STRING_t	*netmask	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IpPool_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_id_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_IpPool;

#ifdef __cplusplus
}
#endif

#endif	/* _IpPool_H_ */
#include <asn_internal.h>
