/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "DNDS"
 * 	found in "./dnds.asn1"
 */

#ifndef	_NetinfoResponse_H_
#define	_NetinfoResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include "DNDSResult.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NetinfoResponse */
typedef struct NetinfoResponse {
	OCTET_STRING_t	 ipAddress;
	OCTET_STRING_t	 netmask;
	DNDSResult_t	 result;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NetinfoResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NetinfoResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _NetinfoResponse_H_ */
#include <asn_internal.h>
