/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "DNDS"
 * 	found in "dnds.asn1"
 */

#ifndef	_NetinfoRequest_H_
#define	_NetinfoRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NetinfoRequest */
typedef NULL_t	 NetinfoRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NetinfoRequest;
asn_struct_free_f NetinfoRequest_free;
asn_struct_print_f NetinfoRequest_print;
asn_constr_check_f NetinfoRequest_constraint;
ber_type_decoder_f NetinfoRequest_decode_ber;
der_type_encoder_f NetinfoRequest_encode_der;
xer_type_decoder_f NetinfoRequest_decode_xer;
xer_type_encoder_f NetinfoRequest_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _NetinfoRequest_H_ */
#include <asn_internal.h>
