/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "DNDS"
 * 	found in "dnds.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_P2pSide_H_
#define	_P2pSide_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum P2pSide {
	P2pSide_client	= 1,
	P2pSide_server	= 2
	/*
	 * Enumeration is extensible
	 */
} e_P2pSide;

/* P2pSide */
typedef long	 P2pSide_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_P2pSide;
asn_struct_free_f P2pSide_free;
asn_struct_print_f P2pSide_print;
asn_constr_check_f P2pSide_constraint;
ber_type_decoder_f P2pSide_decode_ber;
der_type_encoder_f P2pSide_encode_der;
xer_type_decoder_f P2pSide_decode_xer;
xer_type_encoder_f P2pSide_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _P2pSide_H_ */
#include <asn_internal.h>
