/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "DNDS"
 * 	found in "dnds.asn1"
 */

#ifndef	_PeerConnectInfo_H_
#define	_PeerConnectInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>
#include <OCTET_STRING.h>
#include "ConnectState.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PeerConnectInfo */
typedef struct PeerConnectInfo {
	IA5String_t	 certName;
	OCTET_STRING_t	 ipAddr;
	ConnectState_t	 state;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PeerConnectInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PeerConnectInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _PeerConnectInfo_H_ */
#include <asn_internal.h>
