/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "DNDS"
 * 	found in "dnds.asn1"
 */

#ifndef	_SearchRequest_H_
#define	_SearchRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SearchType.h"
#include "ObjectName.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SearchRequest */
typedef struct SearchRequest {
	SearchType_t	 searchtype;
	ObjectName_t	 objectname;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SearchRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SearchRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _SearchRequest_H_ */
#include <asn_internal.h>
