/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "DNDS"
 * 	found in "./dnds.asn1"
 */

#ifndef	_SearchRequest_H_
#define	_SearchRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DNDSObject.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SearchRequest */
typedef DNDSObject_t	 SearchRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SearchRequest;
asn_struct_free_f SearchRequest_free;
asn_struct_print_f SearchRequest_print;
asn_constr_check_f SearchRequest_constraint;
ber_type_decoder_f SearchRequest_decode_ber;
der_type_encoder_f SearchRequest_encode_der;
xer_type_decoder_f SearchRequest_decode_xer;
xer_type_encoder_f SearchRequest_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SearchRequest_H_ */
#include <asn_internal.h>
