/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "DNDS"
 * 	found in "dnds.asn1"
 */

#ifndef	_Topology_H_
#define	_Topology_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Topology {
	Topology_mesh	= 1,
	Topology_hubspoke	= 2,
	Topology_gateway	= 3
	/*
	 * Enumeration is extensible
	 */
} e_Topology;

/* Topology */
typedef long	 Topology_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Topology;
asn_struct_free_f Topology_free;
asn_struct_print_f Topology_print;
asn_constr_check_f Topology_constraint;
ber_type_decoder_f Topology_decode_ber;
der_type_encoder_f Topology_encode_der;
xer_type_decoder_f Topology_decode_xer;
xer_type_encoder_f Topology_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Topology_H_ */
#include <asn_internal.h>
