/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "DNDS"
 * 	found in "./dnds.asn1"
 */

#ifndef	_User_H_
#define	_User_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <PrintableString.h>
#include <IA5String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* User */
typedef struct User {
	unsigned long	 id;
	unsigned long	 contextId;
	PrintableString_t	*name	/* OPTIONAL */;
	PrintableString_t	*password	/* OPTIONAL */;
	PrintableString_t	*firstname	/* OPTIONAL */;
	PrintableString_t	*lastname	/* OPTIONAL */;
	IA5String_t	*email	/* OPTIONAL */;
	long	*role	/* OPTIONAL */;
	long	*status	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} User_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_id_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_contextId_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_User;

#ifdef __cplusplus
}
#endif

#endif	/* _User_H_ */
#include <asn_internal.h>
