/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "DNDS"
 * 	found in "dnds.asn1"
 */

#ifndef	_WebCredential_H_
#define	_WebCredential_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <PrintableString.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* WebCredential */
typedef struct WebCredential {
	unsigned long	 clientId;
	PrintableString_t	*username	/* OPTIONAL */;
	PrintableString_t	*password	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WebCredential_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_clientId_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_WebCredential;

#ifdef __cplusplus
}
#endif

#endif	/* _WebCredential_H_ */
#include <asn_internal.h>
