FROM debian:jessie

RUN apt-get update && \
    apt-get install -y libqt5core5a libqt5network5 make qt5-qmake qtbase5-dev g++
WORKDIR /usr/src/netvirt/android
ENV QT_SELECT=5

ADD . /usr/src/netvirt/android
RUN make desktop-cli

CMD mkdir -p /dev/net && \
    mknod /dev/net/tun c 10 200 && \
    ip tuntap add dev tun0 mode tun && \
    ip address add 10.0.0.2 peer 10.0.0.1 dev tun0 && \
    ip link set tun0 up && \
    build-desktop-cli/netvirt
