FROM debian:jessie

RUN apt-get update && \
    apt-get install g++
WORKDIR /usr/src/netvirt/android/server

ADD ./server/ToyVpnServer.cpp /usr/src/netvirt/android/server/ToyVpnServer.cpp
RUN g++ -o ToyVpnServer ToyVpnServer.cpp

CMD mkdir -p /dev/net && \
    mknod /dev/net/tun c 10 200 && \
    ip tuntap add dev tun0 mode tun && \
    ip address add 10.0.0.1 peer 10.0.0.2 dev tun0 && \
    ip link set tun0 up && \
    ./ToyVpnServer tun0 8000 test -m 1400 -a 10.0.0.2 32 -d 10.0.0.1 -r 0.0.0.0 0
