/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "DNDS"
 * 	found in "dnds.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_ConnState_H_
#define	_ConnState_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ConnState {
	ConnState_connected	= 1,
	ConnState_disconnected	= 2
	/*
	 * Enumeration is extensible
	 */
} e_ConnState;

/* ConnState */
typedef long	 ConnState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConnState;
asn_struct_free_f ConnState_free;
asn_struct_print_f ConnState_print;
asn_constr_check_f ConnState_constraint;
ber_type_decoder_f ConnState_decode_ber;
der_type_encoder_f ConnState_encode_der;
xer_type_decoder_f ConnState_decode_xer;
xer_type_encoder_f ConnState_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ConnState_H_ */
#include <asn_internal.h>
