/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "DNDS"
 * 	found in "dnds.asn1"
 * 	`asn1c -fnative-types`
 */

#include "DNDSObject.h"

static asn_TYPE_member_t asn_MBR_DNDSObject_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DNDSObject, choice.client),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Client,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"client"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DNDSObject, choice.context),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Context,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"context"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DNDSObject, choice.node),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Node,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"node"
		},
};
static asn_TYPE_tag2member_t asn_MAP_DNDSObject_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* client */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* context */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* node */
};
static asn_CHOICE_specifics_t asn_SPC_DNDSObject_specs_1 = {
	sizeof(struct DNDSObject),
	offsetof(struct DNDSObject, _asn_ctx),
	offsetof(struct DNDSObject, present),
	sizeof(((struct DNDSObject *)0)->present),
	asn_MAP_DNDSObject_tag2el_1,
	3,	/* Count of tags in the map */
	0,
	3	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_DNDSObject = {
	"DNDSObject",
	"DNDSObject",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_DNDSObject_1,
	3,	/* Elements count */
	&asn_SPC_DNDSObject_specs_1	/* Additional specs */
};

