/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "DNDS"
 * 	found in "dnds.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_DNDSObjects_H_
#define	_DNDSObjects_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DNDSObject;

/* DNDSObjects */
typedef struct DNDSObjects {
	A_SEQUENCE_OF(struct DNDSObject) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DNDSObjects_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DNDSObjects;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DNDSObject.h"

#endif	/* _DNDSObjects_H_ */
#include <asn_internal.h>
