/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "DNDS"
 * 	found in "dnds.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_NodeConnInfo_H_
#define	_NodeConnInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>
#include <OCTET_STRING.h>
#include "ConnState.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NodeConnInfo */
typedef struct NodeConnInfo {
	IA5String_t	 certName;
	OCTET_STRING_t	 ipAddr;
	ConnState_t	 state;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NodeConnInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NodeConnInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _NodeConnInfo_H_ */
#include <asn_internal.h>
