/*
 * Generated by asn1c-0.9.26 (http://lionet.info/asn1c)
 * From ASN.1 module "DNDS"
 * 	found in "dnds.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_ProvRequest_H_
#define	_ProvRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include <PrintableString.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ProvRequest */
typedef struct ProvRequest {
	PrintableString_t	*certreq	/* OPTIONAL */;
	PrintableString_t	*provCode	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProvRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProvRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _ProvRequest_H_ */
#include <asn_internal.h>
