/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DNDS"
 * 	found in "dnds.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_TerminateRequest_H_
#define	_TerminateRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TerminateRequest */
typedef NULL_t	 TerminateRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TerminateRequest;
asn_struct_free_f TerminateRequest_free;
asn_struct_print_f TerminateRequest_print;
asn_constr_check_f TerminateRequest_constraint;
ber_type_decoder_f TerminateRequest_decode_ber;
der_type_encoder_f TerminateRequest_encode_der;
xer_type_decoder_f TerminateRequest_decode_xer;
xer_type_encoder_f TerminateRequest_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _TerminateRequest_H_ */
#include <asn_internal.h>
