/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "DNDS"
 * 	found in "dnds.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_ConnectState_H_
#define	_ConnectState_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ConnectState {
	ConnectState_connected	= 1,
	ConnectState_disconnected	= 2
	/*
	 * Enumeration is extensible
	 */
} e_ConnectState;

/* ConnectState */
typedef long	 ConnectState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConnectState;
asn_struct_free_f ConnectState_free;
asn_struct_print_f ConnectState_print;
asn_constr_check_f ConnectState_constraint;
ber_type_decoder_f ConnectState_decode_ber;
der_type_encoder_f ConnectState_encode_der;
xer_type_decoder_f ConnectState_decode_xer;
xer_type_encoder_f ConnectState_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ConnectState_H_ */
#include <asn_internal.h>
