/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "DNDS"
 * 	found in "dnds.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_DelRequest_H_
#define	_DelRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DNDSObject.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DelRequest */
typedef DNDSObject_t	 DelRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DelRequest;
asn_struct_free_f DelRequest_free;
asn_struct_print_f DelRequest_print;
asn_constr_check_f DelRequest_constraint;
ber_type_decoder_f DelRequest_decode_ber;
der_type_encoder_f DelRequest_encode_der;
xer_type_decoder_f DelRequest_decode_xer;
xer_type_encoder_f DelRequest_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DelRequest_H_ */
#include <asn_internal.h>
