/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "DNDS"
 * 	found in "dnds.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_DNDSMessage_H_
#define	_DNDSMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "DNMessage.h"
#include "DSMessage.h"
#include <BIT_STRING.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum pdu_PR {
	pdu_PR_NOTHING,	/* No components present */
	pdu_PR_dnm,
	pdu_PR_dsm,
	pdu_PR_ethernet,
	/* Extensions may appear below */
	
} pdu_PR;

/* DNDSMessage */
typedef struct DNDSMessage {
	unsigned long	 version;
	long	 channel;
	struct pdu {
		pdu_PR present;
		union DNDSMessage__pdu_u {
			DNMessage_t	 dnm;
			DSMessage_t	 dsm;
			BIT_STRING_t	 ethernet;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} pdu;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DNDSMessage_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_version_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_DNDSMessage;

#ifdef __cplusplus
}
#endif

#endif	/* _DNDSMessage_H_ */
#include <asn_internal.h>
