/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "DNDS"
 * 	found in "dnds.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_ProvResponse_H_
#define	_ProvResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <PrintableString.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ProvResponse */
typedef struct ProvResponse {
	PrintableString_t	*certificate	/* OPTIONAL */;
	PrintableString_t	*certificateKey	/* OPTIONAL */;
	PrintableString_t	*trustedCert	/* OPTIONAL */;
	OCTET_STRING_t	*ipAddress	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProvResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProvResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _ProvResponse_H_ */
#include <asn_internal.h>
