/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "DNDS"
 * 	found in "dnds.asn1"
 * 	`asn1c -fnative-types`
 */

#include "SearchResponse.h"

static asn_TYPE_member_t asn_MBR_objects_4[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_DNDSObject,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_objects_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_objects_specs_4 = {
	sizeof(struct objects),
	offsetof(struct objects, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_objects_4 = {
	"objects",
	"objects",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_objects_tags_4,
	sizeof(asn_DEF_objects_tags_4)
		/sizeof(asn_DEF_objects_tags_4[0]) - 1, /* 1 */
	asn_DEF_objects_tags_4,	/* Same as above */
	sizeof(asn_DEF_objects_tags_4)
		/sizeof(asn_DEF_objects_tags_4[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_objects_4,
	1,	/* Single element */
	&asn_SPC_objects_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SearchResponse_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SearchResponse, searchtype),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SearchType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"searchtype"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SearchResponse, dndsResult),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DNDSResult,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"dndsResult"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SearchResponse, objects),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_objects_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"objects"
		},
};
static ber_tlv_tag_t asn_DEF_SearchResponse_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SearchResponse_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* searchtype at 187 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* dndsResult at 188 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* objects at 189 */
};
static asn_SEQUENCE_specifics_t asn_SPC_SearchResponse_specs_1 = {
	sizeof(struct SearchResponse),
	offsetof(struct SearchResponse, _asn_ctx),
	asn_MAP_SearchResponse_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* Start extensions */
	4	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SearchResponse = {
	"SearchResponse",
	"SearchResponse",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SearchResponse_tags_1,
	sizeof(asn_DEF_SearchResponse_tags_1)
		/sizeof(asn_DEF_SearchResponse_tags_1[0]), /* 1 */
	asn_DEF_SearchResponse_tags_1,	/* Same as above */
	sizeof(asn_DEF_SearchResponse_tags_1)
		/sizeof(asn_DEF_SearchResponse_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SearchResponse_1,
	3,	/* Elements count */
	&asn_SPC_SearchResponse_specs_1	/* Additional specs */
};

